{"activity":"ghpages","category":"activity-error","message":"activity failed with execption:\nTraceback (most recent call last):\n  File \"/home/scopatz/.local/lib/python3.6/site-packages/rever-0.1.0-py3.6.egg/rever/activity.xsh\", line 59, in __call__\n    self.func(*args, **kwargs)\n  File \"/home/scopatz/.local/lib/python3.6/site-packages/rever-0.1.0-py3.6.egg/rever/activities/ghpages.xsh\", line 64, in _func\n    copy = expand_copy(copy)\n  File \"/home/scopatz/.local/lib/python3.6/site-packages/rever-0.1.0-py3.6.egg/rever/activities/ghpages.xsh\", line 42, in expand_copy\n    if not os.path.exist(src):\nAttributeError: module 'posixpath' has no attribute 'exist'\nrewinding to 49da7a34be1aa08f5d7a9565b86d1645b07c9d14","rev":"6ee2e7b8b878c0861c66eb193ec40e559c52b798","timestamp":1510788487.8806913}
